parameters:
  timesteps: 5000
  dt: 0.001
  mu: 0.05
  sigma: 0.2
  S0: 100
  seq_len: 100
  batch_size: 32
  learning_rate: 0.001
  epochs: 500
  predict_steps: [1, 10, 100]
  jump_intensity: 1.0
  jump_mean: 0.02
  jump_std: 0.05